### ISSUE TITLE
find_in_parent_folders not working as you intend

### ISSUE THREAD

**Issue by yb-jmogavero** [henryjcee/tf_aws_example#1]
https://github.com/henryjcee/tf_aws_example/blob/6cdbfe22b2d48e22f65a335e74e1e587691ad1b0/env/terragrunt.hcl#L3

It's not clear how this would ever work.  Find_in_parent_folders looks UP the directory tree, not down into child folders.  Cloning your repo and running it as described simply does not work.  

Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a env.yaml in any of the parent folders of <mydir>/tf_aws_example/env/terragrunt.hcl.
Cause: Traversed all the way to the root..

**Comment by henryjcee** [comment]
Evening, thanks for the comment. I actually have a big update I've been meaning to make to this whole post and repo as I've extended it for multi-region, reduced the .hcl duplication and make a few smaller tweaks for running the tech stack at Nanumo. Happy to hop on a call and run you through it in the meantime if that's of interest.

Regarding your point, the reason it works as written is that this file gets included into the child .hcls like [here](https://github.com/henryjcee/tf_aws_example/blob/6cdbfe22b2d48e22f65a335e74e1e587691ad1b0/env/prod/iam_roles/terragrunt.hcl#L2) and `find_in_parent_folders()` will then traverse up the filesystem from that point to find `env.yaml`. Would need to dig a bit deeper into the error you're seeing but as I say thanks for the feedback and happy to hop on a call and swap thoughts if that's of interest.

**Comment by henryjcee** [comment]
Yeah so looking at what we're using at the moment, it's a similar idea with a few additions:

```
modules 
|    ...
env
|   _common
|   root
|   base.hcl
|__ prod
     |   env.yaml  
     |   datadog
     |__ eu-west-2
        |   region.yaml
        |__ certs
                terragrunt.hcl
```

`_common` contains `.hcl` files that contain the common tg config e.g. `_common/certs.hcl`:

```
terraform {
  source = "../../../../modules//certs"
}

dependency "lets_encrypt" {
  config_path = "../../lets_encrypt"
}

inputs = {
  nanumo_com_acme_certificate = dependency.lets_encrypt.outputs.nanumo_com_acme_certificate
}

```
Which saves having to repeat it across 3+ envs.

`base.hcl` contains all our provider config as well as the logic to load env vars. Right now it looks like this:

```
locals {
#  Some modules don't have regions (non-AWS ones) so we have to support that
  env_vars = yamldecode(join("\n", [file(find_in_parent_folders("env.yaml")), fileexists("${get_terragrunt_dir()}/../region.yaml") ? file("${get_terragrunt_dir()}/../region.yaml"): ""]))
  aws_root_account_id = "<root_account_id>"
}

# ...and make them available as inputs
inputs = {
  region = try(local.env_vars.region, "eu-west-2")
  env = local.env_vars.env
  aws_account_id = local.env_vars.aws_account_id
  aws_root_account_id = local.aws_root_account_id
}

...
```

Note the use of `find_in_parent_folders()` to pull data from `env.yaml` and `region.yaml`.

Then finally the leaf hcl file `env/prod/eu-west-2/certs/terragrunt.hcl` looks like this:

```
include {
  path = find_in_parent_folders("base.hcl")
}

include "certs" {
  path = "${get_terragrunt_dir()}/../../../_common/certs.hcl"
}
```

keeping our terragrunt configuration as DRY as possible. Hope that helps.

**Comment by yb-jmogavero** [comment]
Hi Henry,  Sure would love to jump on a call and go over the scenario.  What time zone are you in?

 I think looking back on it your intent was to run the terragrunt plan (or terragrunt run-all plan) from a child folder and have it read configs up the directory tree from each child.  Meaning to deploy to multiple accounts in the same run, you'd need to walk the directory tree to each account you want to deploy to and plan/apply in each of them.  Am I interpreting correctly?  

Here's what I've ended up going with for my project.  (The use case is deploying iam roles and eventually other security infra log cloudtrail, config, guard duty, etc to all accounts in the org.  Testing with 3, but will have 20+ in the end)

```
.
├── log-archive
│   ├── account.hcl
│   └── us-west-2
│       ├── iam
│       │   └── terragrunt.hcl
│       └── region.hcl
├── mgmt
│   ├── account.hcl
│   └── us-west-2
│       ├── iam
│       │   └── terragrunt.hcl
│       └── region.hcl
├── security
│   ├── account.hcl
│   └── us-west-2
│       ├── iam
│       │   └── terragrunt.hcl
│       └── region.hcl
└── terragrunt.hcl
```

It needs some work, iam is global so i could move it up to the account level for example, but the provider block in the root `terragrunt.hcl` contains an `assume_role` block that calls `role_arn = "${local.iam_role_arn}"` and then each `account.hcl` specifies the arn of the role being assumed to deploy the infra. 

but to deploy I do have to `cd` into each folder and run my plan/apply commands, so to automate it I'd have to have a control script walk the tree, which feels awkward.  I'm curious to see if your method can accomplish it in a single plan/apply sequence.

**Comment by henryjcee** [comment]
GMT for me and looks like you're in Denver so could do 1700 GMT tomorrow which is 1000MT I think?

> I think looking back on it your intent was to run the terragrunt plan (or terragrunt run-all plan) from a child folder and have it read configs up the directory tree from each child.

Pretty much this yes. So individual modules can be run direct from the leaf directory (e.g. `env/prod/eu-west-2/certs`) with `tg apply` or we have our CI/CD setup to do a `tg run-all plan/apply` from `env/<dev/prod/staging>` which with some path dependencies e.g. 

```
dependencies {
  paths = ["../../../root/aws_accounts"]
}
```

Will run all of the modules in that particular env as well as any additional modules (e.g. commonly from the `root` env which contains some global stuff) as per the dependency graph.

Sounds like you have a similar provider setup to us and I'd be interested to know what happens if you do a `tg run-all plan` from `./`. Will it execute everything? Let me know about a call and get me on henry@nanumo.com in case I miss a reply here.
