### ISSUE TITLE
misssing route53_zone

### ISSUE THREAD

**Issue by chos2205** [henryjcee/tf_aws_example#2]
It seems missing route53_zone module

**Comment by henryjcee** [comment]
Evening, that is correct. Just working on a fix now, will let you know when it's up.

Thanks for the feedback, appreciate it.

**Comment by henryjcee** [comment]
Ok, pushed some updated code and I've included a better README in [here](https://github.com/henryjcee/tf_aws_example/tree/master/modules/route53_zone) that explains how it all works.

Let me know if that helps.

**Comment by chos2205** [comment]
Thanks!
